### ISSUE TITLE
TF Provider supports only ZIP

### ISSUE THREAD

**Issue by Mazorius** [marcofranssen/terraform-provider-curl#151]
Hi,

I like to use this provider but I got this issue during init:

```shell
Error while installing marcofranssen/curl v0.6.0: zip: not a valid zip file
```

From this issue: https://github.com/hashicorp/terraform/issues/26282
I think tar.gz is not supported and zip should be used.

Thanks in advance

**Comment by marcofranssen** [comment]
Fixed the release script.
